### ISSUE TITLE
config.php getting updated but not in-memory copy

### ISSUE THREAD

**Issue by pcolmer** [vvanasten/YOURLS-Change-Password#2]
I'm running YOURLS in a Docker container with a volume mount for /var/www/html/user so that `config.php` exists on the host system and not in the container.

I've activated the change password plugin and, just to be sure, restarted the container.

When I change my password on YOURLS then log out and try to log in with my new password, it fails. If I log in with my old password, it works.

If I then restart the container again, my new password then works.

This suggests that YOURLS isn't picking up/being told that the password has changed. I suspect that YOURLS is loading the config file at the start but not realising the file needs to be reloaded.

I'm not sure if this is a problem with the change password plugin or with YOURLS.

**Comment by vvanasten** [comment]
I'm not super familiar with Docker, but at the end of the day the plugin uses `file_put_contents` to write an updated `/user/config.php` file with the password hash inside the `$yourls_user_passwords` array updated for the current user. 

I agree with your suspicions that YOURLS isn't getting the updated config.php file. Every time you attempt to log in YOURLS should be reading the contents of config.php from the disk. Since after you restart the container the new password works that points to the file being correctly changed on the disk, which is what I expect the plugin to do.

I would check the state of the password hash within the config file, change the password, then examine the file and see if the hash changes within the container.

**Comment by pcolmer** [comment]
I've double-checked and `config.php` is getting updated on the host and, if I check within the running container, the file contents are correct there as well.

I'll raise an issue against YOURLS and reference this one.

Thanks.
